site_name: Unofficial Rheem Eziset Protocol Documentation
repo_url: https://github.com/illuzn/Rheem-Eziset-Protocol/
edit_uri: blob/main/docs/
site_description: These pages seek to document the Rheem Eziset Protocol.
nav:
  - Home: index.md
  - Hardware: hardware.md
  - Network: network.md
  - Logic: logic.md
  - Protocol: protocol.md
  - Home Assistant/ Node-Red: ha.md
  - Home Assistant (Deprecated): ha_old.md
  - Contribute: contribute.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
